### ISSUE TITLE
Add support for Org 9.0

### ISSUE THREAD

**Issue by et2010** [cute-jumper/org-table-sticky-header#1]
Thanks for sharing this. This will be very handy when dealing with long tables. Does it support org 9.0?

**Comment by cute-jumper** [comment]
Sure. Do you have any problem using it with Org 9.0?

**Comment by cute-jumper** [comment]
Closing this due to lack of information. I use Org 9.0 and it works. If you have any problems using it with Org 9.0, feel free to reopen it.
