### ISSUE TITLE
Does not respect column width and alignment

### ISSUE THREAD

**Issue by thecountoftuscany** [cute-jumper/org-table-sticky-header#11]
The sticky header does not respect column widths (defined with \<number\>) as mentioned [here](https://orgmode.org/manual/Column-width-and-alignment.html) so the header and table contents are not aligned properly and look skewed.

![image](https://user-images.githubusercontent.com/14308382/56485789-067a0000-64f3-11e9-9590-f2e3dd3574c7.png)

**Comment by stardiviner** [comment]
I have similar issue:

![image](https://user-images.githubusercontent.com/378699/60413334-2884b280-9c07-11e9-8950-7afef5938875.png)

**Comment by stardiviner** [comment]
I fixed it by small modification.

Here is the screenshot:

![image](https://user-images.githubusercontent.com/378699/60414265-34be3f00-9c0a-11e9-935b-224cc055c00a.png)

I will create a PR soon.

**Comment by stardiviner** [comment]
This is caused by customize `org-table` face.

**Comment by thecountoftuscany** [comment]
@cute-jumper Is there some issue with this PR?

**Comment by cute-jumper** [comment]
Yep. I had a minor question for the PR. Not getting response from @stardiviner (BTW, in general, I think the PR looks great)

**Comment by stardiviner** [comment]
@cute-jumper Aha, sorry for missing this PR comment. The `:underline t` is not required. Just help user to see by separate the header line from table lines.

**Comment by stardiviner** [comment]
@cute-jumper The latest version missed two parentheses at the end of function. My fault. I pushed a fix commit on my repo. will add PR soon.
UPDATE:
https://github.com/cute-jumper/org-table-sticky-header/pull/13
