### ISSUE TITLE
Allow column alignment before headerline

### ISSUE THREAD

**Issue by swhahn** [cute-jumper/org-table-sticky-header#5]
Great package!!!

One thing missing: In my tables I have column width line mostly before headerline as:

| <6>   |           | 
| Col-1 | Col-2 |
|-
| Data |           |

In this case the headerline is not correctly recognized. Org-mode also allows a
table to begin with a line additionally.

With kind regards,
Stefan

**Comment by cute-jumper** [comment]
I see. I have a short discussion about this issue with @theldoria in #2. For now, the header line must be the first line. It is possible to make it more intelligent by skipping the `|---` line or the line containing only the width specifications. I'll try to push some commits when I'm free.

**Comment by cute-jumper** [comment]
I've pushed a commit. Now this package will not consider lines like `|--` or `| <4> |    |` to be the header line. Please report any issues here if the new commit doesn't work or introduces any other bugs. 😄

**Comment by theldoria** [comment]
Please note my comment of your commit, which reminds you of the possible column width and alignment specifier.

**Comment by cute-jumper** [comment]
Thanks @theldoria . It should be fixed now.

**Comment by swhahn** [comment]
Thanks. Works like a charm.

**Comment by cute-jumper** [comment]
Closing this for now. Feel free to reopen it if there is something else that needs to be considered when fetching the real header line.
