### ISSUE TITLE
Indentation of table not same as header

### ISSUE THREAD

**Issue by ddoherty03** [cute-jumper/org-table-sticky-header#6]
Great package.  I deal with long tables a lot.  This is a bit of a nit, but I always use org-indent-mode, so my tables are typically indented depending on where they are in the outline.  Looks like the sticky header is always flush against the left side, so it is out of alignment with the table body.  Would be nice to have it follow the body indent if possible.

**Comment by cute-jumper** [comment]
Thanks for reporting! Should be fixed in the newest commit. Let me know if that doesn't work.

**Comment by ddoherty03** [comment]
Ah, nice!  Thanks for the quick fix.

**Comment by cute-jumper** [comment]
I'm assuming it should work now so I'll close this issue.

**Comment by ddoherty03** [comment]
Yes.  Works on all tables I've tested.  Thanks again.
