### ISSUE TITLE
Save match data is necessary

### ISSUE THREAD

**Issue by swhahn** [cute-jumper/org-table-sticky-header#7]
Hello,
I'm using your package since since several weeks, it's nice. Today I came about a problem
when using query-replace to change the content of an org-table; it throw a exception. 
After digging it down I saw, that the problem occurs if the screen scrolls vertically. The match
data where lost. So it is necessary to save the match data, here is my proposal of change:

```emacs-lisp
@@ -168,7 +168,8 @@ org-table-sticky-header--fetch-header
 (defun org-table-sticky-header--scroll-function (win start-pos)
   (unless (= org-table-sticky-header--last-win-start start-pos)
     (setq org-table-sticky-header--last-win-start start-pos)
-    (org-table-sticky-header--fetch-header)))
+    (save-match-data
+      (org-table-sticky-header--fetch-header))))
 
 ;;;###autoload
 (define-minor-mode org-table-sticky-header-mode
```

With kind regards,
Stefan

**Comment by cute-jumper** [comment]
Thanks for reporting this! I've applied the changes. Should be in Melpa soon.
